In [2]:
import numpy as np
import cPickle as cp
np.set_printoptions(suppress=True)

In [3]:
with open('test.save', 'rb') as pf:
    data = cp.load(pf)

In [4]:
activations = data[0]
labels = data[1]
predictions = data[2]

In [5]:
print predictions
print labels

[468 268 244 627 281 436 345 466 742 527]
[468 268 256 627 282 436 345 466 782 782]


In [6]:
np.nonzero(activations[0])

(array([ 0,  0,  0, ..., 13, 13, 13]),
 array([ 0,  0,  0, ..., 13, 13, 13]),
 array([  0,   1,   8, ..., 506, 507, 509]))

In [7]:
activations.shape

(10, 14, 14, 512)

In [8]:
(10*14*14*512)-207755

795765

In [9]:
a = np.sum(activations, axis=(1,2))

In [10]:
a.shape


(10, 512)

In [13]:
with open('/deepack/dumps_relu/test_0.save', 'rb') as pf:
    batch_0 = cp.load(pf)

In [14]:
layers = []
for itr,item in enumerate(batch_0[0]):
    layers.append(item)    
labels = batch_0[1]
predictions = batch_0[2]

labels.shape
predictions.shape

(150,)

In [15]:
for itr, m in enumerate(layers):
    layers[itr] = np.hstack((layers[itr], layers[itr]))

In [16]:
layers[0].shape


(150, 128)

In [17]:
layers = []
for itr,item in enumerate(batch_0[0]):
    layers.append(item)    
labels = batch_0[1]
predictions = batch_0[2]

import tqdm
for itr in range(425):
    with open('/deepack/dumps_relu/test_' + str(itr+1) + '.save', 'rb') as pf:
        batch = cp.load(pf)
    batch_layers = []
    for itr,item in enumerate(batch[0]):
        batch_layers.append(item)    
    batch_labels = batch[1]
    batch_predictions = batch[2]
    
    for idx, m in enumerate(layers):
        layers[idx] = np.vstack((layers[idx], batch_layers[idx]))
    labels = np.hstack((labels, batch_labels))
    predictions = np.hstack((predictions, batch_predictions))

In [18]:
print labels.shape
print predictions.shape
print layers[0].shape

(63900,)
(63900,)
(63900, 64)


In [19]:
with open('/deepack/relu_summed_activations.save', 'wb') as pf:
        cp.dump([layers, labels, predictions], pf, cp.HIGHEST_PROTOCOL)

In [20]:
layers[0].shape

(63900, 64)

In [21]:
print np.min(layers[0])

0.0


In [ ]:
with open('/deepack/dumps_relu/test_0.save', 'rb') as pf:
    batch_0 = cp.load(pf)

layers = batch_0[0] 
labels = batch_0[1]
predictions = batch_0[2]

import tqdm
for itr in range(425):
    with open('/deepack/dumps_relu/test_' + str(itr+1) + '.save', 'rb') as pf:
        batch = cp.load(pf)
    batch_layers = batch[0]
    batch_labels = batch[1]
    batch_predictions = batch[2]
    
    for idx, m in enumerate(layers):
        layers[idx] = np.vstack((layers[idx], batch_layers[idx]))
    labels = np.hstack((labels, batch_labels))
    predictions = np.hstack((predictions, batch_predictions))